season: 2024
rounds: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
cache_dir: fastf1_cache
processed_table: data/season=2024/driver_race_table.parquet
artifacts_dir: artifacts
metrics_dir: artifacts/metrics
models_dir: artifacts/models
rolling_k: 5
holdout_rounds: [21,22,23,24]
